Complete style
shaqayq/BookStore pull request #5
Opened 2022-08-19 21:43 UTC by shaqayq

In this part of the project, I applied all styles to the page according to the `Zeplin `template , and i also set random numbers for each progress percentage.

2022-08-19 22:25 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @shaqayq, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ You used Gitflow correctly
✅ No linter error
✅ README is okay

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-08-19 22:25 UTC, AmaduKamara commented on src/style/navbar.css
> +}
- [ ] It would be nice if you could make the elements in the navbar span the end of the navbar just as it's in the original design. The user icon needs to be at the right end of the navbar. Kindly work on that 👍

2022-08-19 22:25 UTC, AmaduKamara commented on src/style/home.css
> +}
- [ ] Kindly make the boot item elements span to the end. Currently, you're having empty space holding nothing at the moment and the experience does not match the original design. Please see the arrows I marked in red and make the boot item reaches the end just as it is in the original design.
- [ ] I noticed that you forgot to add the progress circle on the book item. I marked it in red in the screenshot below. Please add that in order for your design to match the original design 💪

![image](https://user-images.githubusercontent.com/50941074/185713486-a5d87a7a-33c1-4295-9b07-81b975427703.png)

2022-08-19 22:25 UTC, AmaduKamara commented on src/style/form.css
>  }
- [ ] Kindly make the form elements span to the end. Currently, you're having empty space from the add book button to the end holding nothing at the moment and the experience does not match the original design. Please see the arrows I marked in red and make the form elemsts reach the end just as it is in the original design. 👍

2022-08-19 22:25 UTC, AmaduKamara commented on src/style/page.css
> +}
- [ ] Kindly remove the padding from the body. The design shown in Zeplin is a template design done by a UI/UX designer with the idea of how you should create that design. You should take the whole space of the entire body with no padding. I edited your code and removed the padding and height, and everything looked fine. Kindly work on it.

You can set the body styles to have the following:
```mdx
body {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  background-color: #f5f6fa;
}
```

**With the code above, the container styles used are no longer needed.**
Kindly work on them 👍

2022-08-20 07:45 UTC, shaqayq commented on src/style/page.css
> +}
@AmaduKamara!
Thank you for reviewing my code and for your feedback about it. I'm going to fix all of it. :blush:

2022-08-20 08:06 UTC, mwanawabangona approved these changes
Hi @shaqayq,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good implementation of the requested changes !! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 08:14 UTC, merged